"""
Vidyut Migrations for basic_app

This package contains database migrations generated by Vidyut CLI.
Migrations are applied in order based on their timestamp prefix.

Usage:
    vidyut makemigrations --app models --name <name>  # Generate new migration
    vidyut migrate --migrations-dir migrations        # Apply pending migrations
    vidyut status                                     # Check migration status
"""
