"""
Aksara Migrations for basic_app

This package contains database migrations generated by Aksara CLI.
Migrations are applied in order based on their timestamp prefix.

Usage:
    aksara makemigrations --app models --name <name>  # Generate new migration
    aksara migrate --migrations-dir migrations        # Apply pending migrations
    aksara status                                     # Check migration status
"""
