"""
TypeScript SDK generation for Aksara ModelViewSets.

v0.5.45: Generates a fetch-based CRUD client from discovered ViewSets.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date, datetime
from decimal import Decimal
from types import UnionType
from typing import TYPE_CHECKING, Any, Union, get_args, get_origin
from uuid import UUID

from pydantic import BaseModel

from aksara.core.discovery import auto_discover_viewsets

if TYPE_CHECKING:
    from aksara.api.viewsets import ModelViewSet


@dataclass(slots=True)
class ViewSetSdkSpec:
    """Resolved SDK metadata for a single ModelViewSet."""

    model_name: str
    prefix: str
    create_schema: type[BaseModel]
    update_schema: type[BaseModel]
    read_schema: type[BaseModel]
    filter_fields: list[str]
    search_enabled: bool
    ordering_enabled: bool
    pagination_kind: str = "limit_offset"


def _pagination_kind(pagination_class: type | None) -> str:
    """Map a ViewSet pagination class to its generated client contract."""
    from aksara.api.pagination import (
        CursorPagination,
        LimitOffsetPagination,
        PageNumberPagination,
    )

    if pagination_class is None or issubclass(pagination_class, LimitOffsetPagination):
        return "limit_offset"
    if issubclass(pagination_class, PageNumberPagination):
        return "page_number"
    if issubclass(pagination_class, CursorPagination):
        return "cursor"
    return "custom"


def discover_viewset_sdk_specs(views_module: str | None = None) -> list[ViewSetSdkSpec]:
    """Discover ViewSets and resolve their CRUD schema metadata."""
    specs: list[ViewSetSdkSpec] = []
    for viewset_cls in auto_discover_viewsets(views_module=views_module):
        viewset = viewset_cls()
        specs.append(
            ViewSetSdkSpec(
                model_name=viewset.model.__name__,
                prefix=viewset.prefix.rstrip("/"),
                create_schema=viewset.create_schema,
                update_schema=viewset.update_schema,
                read_schema=viewset.read_schema,
                filter_fields=viewset.get_filter_fields(),
                search_enabled=bool(viewset.search_fields),
                ordering_enabled=bool(viewset.ordering_fields or viewset.ordering),
                pagination_kind=_pagination_kind(viewset.pagination_class),
            )
        )
    return specs


def generate_typescript_sdk_from_discovery(views_module: str | None = None) -> str:
    """Generate the TypeScript SDK from auto-discovered ViewSets."""
    return generate_typescript_sdk(discover_viewset_sdk_specs(views_module=views_module))


def generate_typescript_sdk(viewsets: list[ViewSetSdkSpec | type[ModelViewSet]]) -> str:
    """Generate a fetch-based TypeScript SDK for CRUD ViewSets."""
    specs = [_coerce_viewset_spec(viewset) for viewset in viewsets]

    schema_map: dict[str, type[BaseModel]] = {}
    for spec in specs:
        schema_map[spec.create_schema.__name__] = spec.create_schema
        schema_map[spec.update_schema.__name__] = spec.update_schema
        schema_map[spec.read_schema.__name__] = spec.read_schema

    sections = [
        "/* Auto-generated by `aksara generate sdk --language typescript` */",
        "",
        "export type QueryValue = string | number | boolean | null | undefined;",
        "",
        "export interface PaginatedResponse<T> {",
        "  count: number;",
        "  limit: number;",
        "  offset: number;",
        "  results: T[];",
        "}",
        "",
        "export interface PageNumberPaginatedResponse<T> {",
        "  count: number;",
        "  page: number;",
        "  size: number;",
        "  total_pages: number;",
        "  results: T[];",
        "}",
        "",
        "export interface CursorPaginatedResponse<T> {",
        "  count: number;",
        "  next_cursor: string | null;",
        "  results: T[];",
        "}",
        "",
        "export type CustomPaginatedResponse<T> = Record<string, unknown> & { results: T[] };",
        "",
        "export interface DeleteResponse {",
        "  deleted: boolean;",
        "  id: string;",
        "}",
        "",
        "export interface ClientOptions {",
        "  baseUrl?: string;",
        "  headers?: HeadersInit;",
        "  fetch?: typeof fetch;",
        "}",
        "",
    ]

    for schema_name in sorted(schema_map):
        sections.append(_render_interface(schema_name, schema_map[schema_name]))
        sections.append("")

    for spec in specs:
        params_interface = _render_list_params_interface(spec)
        if params_interface:
            sections.append(params_interface)
            sections.append("")

    sections.extend([
        "function buildQueryString(params: object = {}): string {",
        "  const search = new URLSearchParams();",
        "  for (const [key, value] of Object.entries(params)) {",
        "    if (value === undefined || value === null) continue;",
        "    search.append(key, String(value));",
        "  }",
        "  const query = search.toString();",
        "  return query ? `?${query}` : '';",
        "}",
        "",
        "export class AksaraClient {",
        "  constructor(private readonly options: ClientOptions = {}) {}",
        "",
        "  private async request<T>(path: string, init: RequestInit & { params?: object } = {}): Promise<T> {",
        "    const fetchImpl = this.options.fetch ?? fetch;",
        "    const url = `${this.options.baseUrl ?? ''}${path}${buildQueryString(init.params)}`;",
        "    const headers = new Headers(this.options.headers ?? {});",
        "    if (init.body !== undefined && !headers.has('Content-Type')) {",
        "      headers.set('Content-Type', 'application/json');",
        "    }",
        "",
        "    const response = await fetchImpl(url, { ...init, headers });",
        "    if (!response.ok) {",
        "      throw new Error(`Aksara request failed: ${response.status} ${response.statusText}`);",
        "    }",
        "",
        "    if (response.status === 204) {",
        "      return undefined as T;",
        "    }",
        "",
        "    return response.json() as Promise<T>;",
        "  }",
        "",
    ])

    for spec in specs:
        sections.extend(_render_client_methods(spec))

    sections.extend([
        "}",
        "",
        "export function createAksaraClient(options: ClientOptions = {}): AksaraClient {",
        "  return new AksaraClient(options);",
        "}",
    ])

    return "\n".join(sections).rstrip() + "\n"


def _coerce_viewset_spec(viewset: ViewSetSdkSpec | type[ModelViewSet]) -> ViewSetSdkSpec:
    if isinstance(viewset, ViewSetSdkSpec):
        return viewset

    instance = viewset()
    return ViewSetSdkSpec(
        model_name=instance.model.__name__,
        prefix=instance.prefix.rstrip("/"),
        create_schema=instance.create_schema,
        update_schema=instance.update_schema,
        read_schema=instance.read_schema,
        filter_fields=instance.get_filter_fields(),
        search_enabled=bool(instance.search_fields),
        ordering_enabled=bool(instance.ordering_fields or instance.ordering),
        pagination_kind=_pagination_kind(instance.pagination_class),
    )


def _render_interface(name: str, schema: type[BaseModel]) -> str:
    lines = [f"export interface {name} {{"]
    for field_name, field in schema.model_fields.items():
        optional = "?" if not field.is_required() else ""
        field_type = _python_type_to_ts(field.annotation)
        lines.append(f"  {field_name}{optional}: {field_type};")
    lines.append("}")
    return "\n".join(lines)


def _render_list_params_interface(spec: ViewSetSdkSpec) -> str:
    interface_name = f"{spec.model_name}ListParams"
    lines = [f"export interface {interface_name} {{"]

    if spec.pagination_kind == "limit_offset":
        lines.extend(["  limit?: number;", "  offset?: number;"])
    elif spec.pagination_kind == "page_number":
        lines.extend(["  page?: number;", "  size?: number;"])
    elif spec.pagination_kind == "cursor":
        lines.extend(["  cursor?: string;", "  page_size?: number;"])

    if spec.search_enabled:
        lines.append("  search?: string;")
    if spec.ordering_enabled:
        lines.append("  ordering?: string;")
    for field_name in spec.filter_fields:
        lines.append(f"  {field_name}?: QueryValue;")

    lines.append("}")
    return "\n".join(lines)


def _render_client_methods(spec: ViewSetSdkSpec) -> list[str]:
    collection_name = _path_to_pascal_case(spec.prefix)
    item_name = _to_pascal_case(spec.model_name)
    base_path = f"{spec.prefix}/"
    resource_path = spec.prefix
    params_type = f"{spec.model_name}ListParams"
    read_type = spec.read_schema.__name__
    create_type = spec.create_schema.__name__
    update_type = spec.update_schema.__name__
    pagination_type = {
        "limit_offset": "PaginatedResponse",
        "page_number": "PageNumberPaginatedResponse",
        "cursor": "CursorPaginatedResponse",
        "custom": "CustomPaginatedResponse",
    }[spec.pagination_kind]

    return [
        f"  async list{collection_name}(params: {params_type} = {{}}): Promise<{pagination_type}<{read_type}>> {{",
        f"    return this.request<{pagination_type}<{read_type}>>('{base_path}', {{ params }});",
        "  }",
        "",
        f"  async get{item_name}(pk: string): Promise<{read_type}> {{",
        f"    return this.request<{read_type}>(`{resource_path}/${{encodeURIComponent(pk)}}`);",
        "  }",
        "",
        f"  async create{item_name}(data: {create_type}): Promise<{read_type}> {{",
        f"    return this.request<{read_type}>('{base_path}', {{",
        "      method: 'POST',",
        "      body: JSON.stringify(data),",
        "    });",
        "  }",
        "",
        f"  async update{item_name}(pk: string, data: {update_type}): Promise<{read_type}> {{",
        f"    return this.request<{read_type}>(`{resource_path}/${{encodeURIComponent(pk)}}`, {{",
        "      method: 'PATCH',",
        "      body: JSON.stringify(data),",
        "    });",
        "  }",
        "",
        f"  async delete{item_name}(pk: string): Promise<DeleteResponse> {{",
        "    return this.request<DeleteResponse>(",
        f"      `{resource_path}/${{encodeURIComponent(pk)}}`,",
        "      { method: 'DELETE' },",
        "    );",
        "  }",
        "",
    ]


def _python_type_to_ts(annotation: Any) -> str:
    origin = get_origin(annotation)
    args = get_args(annotation)

    if origin in (Union, UnionType):
        rendered = [_python_type_to_ts(arg) for arg in args if arg is not type(None)]
        if any(arg is type(None) for arg in args):
            rendered.append("null")
        return " | ".join(dict.fromkeys(rendered))

    if origin in (list, tuple):
        item_type = _python_type_to_ts(args[0]) if args else "unknown"
        return f"{item_type}[]"

    if origin is dict:
        return "Record<string, unknown>"

    if isinstance(annotation, type) and issubclass(annotation, BaseModel):
        return annotation.__name__

    if annotation in (str, UUID, datetime, date, Decimal):
        return "string"
    if annotation in (int, float):
        return "number"
    if annotation is bool:
        return "boolean"
    if annotation in (dict, list, Any):
        return "unknown"

    return "unknown"


def _path_to_pascal_case(prefix: str) -> str:
    parts = [part for part in prefix.strip("/").replace("-", "_").split("/") if part]
    if not parts:
        return "Items"
    return "".join(_to_pascal_case(part) for part in parts[-1].split("."))


def _to_pascal_case(value: str) -> str:
    return "".join(chunk.capitalize() for chunk in value.replace("-", "_").split("_") if chunk)


__all__ = [
    "ViewSetSdkSpec",
    "discover_viewset_sdk_specs",
    "generate_typescript_sdk",
    "generate_typescript_sdk_from_discovery",
]
