name: Deploy Docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install mkdocs-material mkdocs-autorefs mike "pymdown-extensions>=10.21.3"

      - name: Deploy
        run: mkdocs gh-deploy --force -f docs/mkdocs.yml
